### ISSUE TITLE
Restart with snap restart

### ISSUE THREAD

**Issue by stuartlangridge** [samthor/https-forward#1]
The docs suggest SIGHUPping the binary to make it reread the config file, but `snap restart https-forward` is probably easier to remember in the snap's own description (although will actually do a restart rather than just a re-read, so maybe it's not useful for a deployed thing).

**Comment by samthor** [comment]
Made the note in the Snap description (and in `snapcraft.yaml`)—actually it's not clear whether what's in `snapcraft.yaml` overwrites any changes in the web interface when I republish.
