### ISSUE TITLE
Let'sEncrypt has deprecated the ACMEv1 protocol; the snap for this tool needs recompiled against newer Go packages.

### ISSUE THREAD

**Issue by nestor-custodio** [samthor/https-forward#2]
Per [this Let'sEncrypt post re: "End of Life Plan for ACMEv1"](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430), the ACMEv1 protocol is no longer (as of June 2020) allowing cert generation requests for new domains. The issue was announced some time ago and the relevant Go packages were updated back in October 2019, but the `https-forward` Snap package was unfortunately built shortly before that.

Would it be at all possible for you to recompile and re-publish the Snap package using the latest "golang.org/x/crypto/acme" and "golang.org/x/crypto/acme/autocert" packages?

At the moment, anyone attempting to use `https-forward` for newly-created domains is seeing the following error in their syslog:
```
http: TLS handshake error from {{ letsencrypt server ip and port }}: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

**Comment by samthor** [comment]
I'll rebuild and upload again in the next day or so. Thanks for the notice,
I haven't added any new domains to my config since I set it up.

It's also nice to know folks find this useful!

**Comment by samthor** [comment]
I released a new version to stable on Snapcraft. I also pushed a new `go.mod` file so the dependency it's using is a lot more clear. I tested the old version on an unknown domain (fails), and the new version (succeeds).

Let me know if it works for you.

**Comment by samthor** [comment]
I think this ix fixed.

**Comment by nestor-custodio** [comment]
Just now checking back in on this, and it's working great! Many thanks.
